/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Project, BlogPost } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    titleEN: 'King Salman Financial Tower',
    titleAR: 'برج الملك سلمان المالي',
    category: 'glass',
    categoryEN: 'Structural Glass',
    categoryAR: 'هياكل زجاجية',
    locationEN: 'Riyadh, KSA',
    locationAR: 'الرياض، المملكة العربية السعودية',
    year: '2024',
    sectorEN: 'Government',
    sectorAR: 'حكومي',
    complexityEN: 'Ultra-High',
    complexityAR: 'فائق الدقة',
    scaleEN: '45,000 m²',
    scaleAR: '٤٥,٠٠٠ م²',
    descriptionEN: 'A masterclass in structural glass, utilizing specialized insulated units to withstand extreme thermal variance.',
    descriptionAR: 'تحفة معمارية في الزجاج الإنشائي، تستخدم وحدات زجاجية معزولة مخصصة لتحمل الفوارق الحرارية الشديدة.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvwblNQmF23c_-OuBV0Z0mf899U3_IkjyA5GnwYGAucjLJr5dMn4fIRHOfRhrQXKQp1a9UF4SKTzcHO07m1-nUIN8f_QUAjLWOljnWsKMOYjU7ZIn6cThWq5YIMviz3Qd7OUCZHsN6q0oRTv7_eVjGrBEZw7gJy4I-LzfztGObl7J5yG9JI_9gnbij6SjS2w2HIjWEm3bHFsUza4MeB5TPRd7ny3i0jgWuZ4MUHoJJl342TdyBkVCpsyd88Cfw5CrSk5MCpK67kb14',
    featured: true
  },
  {
    id: '2',
    titleEN: 'NEOM Infrastructure Hub',
    titleAR: 'مجمع بنيوم الإنشائي',
    category: 'iron',
    categoryEN: 'Steel Systems',
    categoryAR: 'أعمال حديد',
    locationEN: 'NEOM, KSA',
    locationAR: 'نيوم، المملكة العربية السعودية',
    year: 'Ongoing',
    sectorEN: 'Vision 2030',
    sectorAR: 'رؤية ٢٠٣٠',
    complexityEN: 'Advanced Structural',
    complexityAR: 'هيكل إنشائي متقدم',
    scaleEN: '120,000 m²',
    scaleAR: '١٢٠,٠٠٠ م²',
    materialEN: 'Hardened Steel',
    materialAR: 'فولاذ مقسى',
    statusEN: 'Active Phase',
    statusAR: 'تحت التنفيذ',
    descriptionEN: 'Pioneering modular steel structures designed for rapid deployment in high-velocity desert environments.',
    descriptionAR: 'هياكل فولاذية نمطية رائدة صممت للتركيب السريع في البيئات الصحراوية ذات الرياح والسرعات العالية.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMnLDv35oEIlyXRgKy3LWwpROa09JaxlklFhgfUcCYnJsXR5yE3do-MNglVqtnZyeOJ79ALeaMSwzMztQ2PO4W0RcFPVEaPzdd8t8Gw2mGbP8044xWAvpE-6-q1-J_nWPmoHhjof27zsYyk1erwGEC6iFXB2HVKXmEtsS5DiD8HrqTbBqRFtrPZa5-MAbLLjWu-fR_-fw3g0jgKdsr0ADAqFxuC8YZJ0p0taaMAr9xj3kPl-crFJZugJfvuNMC6ZSRQTxIIUZocJ4g',
    featured: true
  },
  {
    id: '3',
    titleEN: 'Red Sea Global Pavilion',
    titleAR: 'جناح البحر الأحمر العالمي',
    category: 'glass',
    categoryEN: 'Sustainable Structural',
    categoryAR: 'هياكل مستدامة',
    locationEN: 'Red Sea, KSA',
    locationAR: 'البحر الأحمر، المملكة العربية السعودية',
    year: '2023',
    sectorEN: 'Luxury Tourism',
    sectorAR: 'سياحة فاخرة',
    complexityEN: 'CNC Parametric',
    complexityAR: 'معتمد على الـ CNC',
    scaleEN: '18,500 m²',
    scaleAR: '١٨,٥٠٠ م²',
    focusEN: 'Sustainable Materials',
    focusAR: 'مواد مستدامة',
    descriptionEN: 'Bespoke structural solutions that blend architectural audacity with environmental sensitivity.',
    descriptionAR: 'حلول إنشائية مخصصة تجمع بين الجرأة المعمارية والاهتمام التام بالسلامة والبيئة المستدامة.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAeXd_bsxIZ523NTAhdnr374o56ikad_BtTVJwWIwQCADfORBs28IQcapnWhHr_d8K3amACjUId2MiQEKt6mA8zyS-TdAB9fCvMs594dvGZS9bolZzlz91PkS-Td1aFw4NKPRg0bpm_5SyyAsXRN1YO3Yrz2tP3xIFJoII2TZf2OM2aKTaIGiz-BplENh_XB6x63o1H_vO74XQ3RbFVyvh1PmWmzlRXd1UcIkFYKqDZ8h1AM_2f_clnNqGfnIB_ht46rUVTjNGdbF5H',
    featured: true
  },
  {
    id: '4',
    titleEN: 'Commercial Crystal Tower',
    titleAR: 'برج الكريستال التجاري',
    category: 'aluminium',
    categoryEN: 'Aluminum Systems',
    categoryAR: 'واجهات ألمنيوم',
    locationEN: 'Riyadh, KSA',
    locationAR: 'الرياض، المملكة العربية السعودية',
    year: '2024',
    sectorEN: 'Commercial Landmark',
    sectorAR: 'تجاري رائد',
    scaleEN: '25,000 m²',
    scaleAR: '٢٥,٠٠٠ م²',
    descriptionEN: 'Advanced aluminum curtain wall systems seamlessly integrated with premium performance structural glass.',
    descriptionAR: 'أنظمة واجهات ألمنيوم متطورة مدمجة بسلاسة مع زجاج إنشائي ذو أداء فائق لعزل الصوت والحرارة.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDqlrwHcNt2VRqEMfO73px9Vmxt-L3lqQkb9Z9Ic8wI-Ni5nbyg3EdqYEcALDRyItBnvlZdhT3R0REdFKYGBxZ_dNQ7-q52XpgCuaoczp3r943lDomB3ge4cjixLDCBDVBTaJeRU3uCpEnAC8urEUKHRb-EsF0lCd_s4yBLak2G6eWTt1gDuhifEqG8bwolOmqlCludTY2XiyP0UU4trFEqMcXSvPqT3ISW-j6ikGon39ZKm0JfC22hGJUVpoZx6L0zBim6zzseeqJr'
  },
  {
    id: '5',
    titleEN: 'Al Nakheel Mall Atrium',
    titleAR: 'أتريوم مجمع النخيل',
    category: 'glass',
    categoryEN: 'Structural Glass',
    categoryAR: 'هياكل زجاجية',
    locationEN: 'Jeddah, KSA',
    locationAR: 'جدة، المملكة العربية السعودية',
    year: '2023',
    sectorEN: 'Retail Complex',
    sectorAR: 'مجمع تجاري',
    scaleEN: '12,000 m²',
    scaleAR: '١٢,٠٠٠ م²',
    descriptionEN: 'High-transparency frameless structural glass atrium designed with minimal visible steel connectors.',
    descriptionAR: 'أتريوم زجاجي إنشائي شفاف بدون فواصل مصمم بأقل قدر من الروابط الفولاذية المرئية لتعظيم النفاذية الضوئية.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvNMXhx_PtZEjUvGER6vEwXdB5cRdkvrltMht8WC9l3SEbK28C07yPkcox9J-zjOUlBCKx9oW4smjdPDKeaXIpjWAgJy3ZnoCagzkfdJjlZ9bOviZBCRjR2Mz-JHQf6rpE0bA6Jf6NxI1oJDauUGz7QT3OxPTqIbJAc--XiSVUcy9fe_W0rzPOitHObQsXeDUscnLk143ZL-RXCIqLGuSOuaWtrpLFgC5Thy8YAJeu0ijswRmR5Uzmnybshd_sVTo8bBAcI0w6NkQY'
  },
  {
    id: '6',
    titleEN: 'Al Naseem Private Villa',
    titleAR: 'فيلا النسيم الخاصة',
    category: 'iron',
    categoryEN: 'Ornamental Iron',
    categoryAR: 'أعمال حديد',
    locationEN: 'Khobar, KSA',
    locationAR: 'الخبر، المملكة العربية السعودية',
    year: '2024',
    sectorEN: 'Luxury Residential',
    sectorAR: 'سكني فاخر',
    scaleEN: '3,200 m²',
    scaleAR: '٣,٢٠٠ م²',
    descriptionEN: 'Exquisite ornamental steel and iron structures blending neoclassical aesthetics with modern clean fabrication.',
    descriptionAR: 'أعمال حديد مزخرفة فائقة الفخامة تدمج بين الجمال الكلاسيكي ودقة التصنيع الهندسي الحديث.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlI6giCcQB-rUvweBJJ-EAjJ2Qq6h0olzrcPKvnwcrqQw436rXYn789VL75xMSuDImoLKJAyQvjfA4_-aVeGjpW95RHsvMDV_RrhzN3jsRpcJ0T2nj7kudYoe99c5Ns8jw0PSiPB8Z_1uvcnrrU6-IHJqKzCyZtBp2f2t6NiwlgM-c5xP23fie1Qa25Fp6Vd8g72xTnqxMvUmqVqrAG2_pMHYOECspMCI4H8E4TZt-pp-X-ZWEy6v1hjs2cziW2PcYaBY-77teAFKU'
  },
  {
    id: '7',
    titleEN: 'Industrial Innovation Complex',
    titleAR: 'مجمع الابتكار الصناعي',
    category: 'aluminium',
    categoryEN: 'Aluminum Systems',
    categoryAR: 'واجهات ألمنيوم',
    locationEN: 'Jubail, KSA',
    locationAR: 'الجبيل، المملكة العربية السعودية',
    year: '2023',
    sectorEN: 'Industrial R&D',
    sectorAR: 'بحثي صناعي',
    scaleEN: '35,000 m²',
    scaleAR: '٣٥,٠٠٠ م²',
    descriptionEN: 'Robust aluminum cladding panels treated to resist highly aggressive marine and chemical environmental dynamics.',
    descriptionAR: 'تكسية ألمنيوم فائقة المتانة تمت معالجتها لمقاومة أقسى العوامل الجوية والظروف البيئية البحرية والكيميائية.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDThd-WgATXSWPGf34k60Y9gU_Fp5HXLZf9TQfJZfcdJFAQ0FojZZnbYkHWv4XzgMCwt47kAawrCIcZWA01A9xFLFyfSk4-YUaFfVFG0wtYfufH5Qqc-nP_CicFqhX3L73xEnZYZpu1Vi-KCjyNmo9gEoHWaQLsv5XNYJvQqm9aRZJU7eorQiAJSfAVDXqPAUR7dC2GPLGPOj2UyMTaZetg_ih6B9GLc_uW9_gksFCeIUSxQtIP4CVgmIN2aeILdqSSflW2Z2g_P-Xa'
  },
  {
    id: '8',
    titleEN: 'Rolls Royce Showroom',
    titleAR: 'معرض رولز رويس',
    category: 'glass',
    categoryEN: 'Structural Glass',
    categoryAR: 'هياكل زجاجية',
    locationEN: 'Riyadh, KSA',
    locationAR: 'الرياض، المملكة العربية السعودية',
    year: '2023',
    sectorEN: 'Luxury Commercial',
    sectorAR: 'تجاري فاخر',
    scaleEN: '1,500 m²',
    scaleAR: '١,٥٠٠ م²',
    descriptionEN: 'Ultrawide spider glass facade systems utilizing premium low-iron glass of supreme architectural clarity.',
    descriptionAR: 'واجهات Spider Glass فائقة العرض والوضوح، باستخدام زجاج منخفض الحديد لضمان الشفافية والنقاء البصري المطلق.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCj6ujoVoJrgwr7_SM4IkWKmQ0g-6xEaO8h3m6OYGus18fY-bNHGDPAF4jph6YbhDIcjqZ67ek6D-cKKRsaZas0HJIsQyuWwGjY_luHLwyZze3kPRg0KQwcM7MLCcT0Hq0rAgrqDb485qtDrWPbt-Kz66pGU66ztQD0e5LFvGWmWdzxlpF7qcPsleej42OL-X2qgZrbYQKhQNZCxNte3z28ACD6e-G6Im9DEsSlXh4YPfk_-K0arDD5TVE0g1wvSkWC2oue_QRDN0co'
  },
  {
    id: '9',
    titleEN: 'Smart Pedestrian Bridge',
    titleAR: 'جسر المشاة الذكي',
    category: 'iron',
    categoryEN: 'Steel Systems',
    categoryAR: 'أعمال حديد',
    locationEN: 'KAFD, Riyadh',
    locationAR: 'مركز الملك عبدالله المالي، الرياض',
    year: '2023',
    sectorEN: 'Urban Infrastructure',
    sectorAR: 'بنية تحتية حضرية',
    scaleEN: '4,800 m²',
    scaleAR: '٤,٨٠٠ م²',
    descriptionEN: 'Heavy structural steel pedestrian bridge meticulously fitted with customized laser-cut geometric lattices.',
    descriptionAR: 'هيكل جسر مشاة فولاذي عملاق متكامل بزخارف وتفاصيل هندسية مدمجة مقصوصة بدقة الليزر.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7AbIbz53C_YURvbfL7IVSBiFB8YdS561Z73FqKXBlFaETJZReMjGUVLk6cfSR8JekGMFmxaZB5lXI9VX2q-iR0FGonumLvrKjT31CY9w4d1dY4ODxTEqwf9MRU5D_bphcM7zk3tigIPqVEC6cAjuIsIf4L-J1iDlUMXjWPfGB9mTkAHxKfcFTXITHDg1rSoS9GQQex0XAskrher-7TsLzL76NR6EbbMnAir8v3HKA3h9s6gt6-QpeLASxXuZ5qjDx2I6TinBVkv3g'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    titleEN: 'The Future of Smart Glass Facades in Megaprojects',
    titleAR: 'مستقبل الواجهات الزجاجية الذكية في المشاريع العملاقة',
    excerptEN: 'Discover how modern glass technology achieves critical thermal insulation and smart lighting in luxury skyscrapers.',
    excerptAR: 'كيف تساهم التقنيات الحديثة في تحسين كفاءة الطاقة وتوفير بيئة عمل استثنائية من خلال زجاج ذكي يتكيف مع الطقس الوعر في المملكة.',
    categoryEN: 'Technical Studies',
    categoryAR: 'دراسات تقنية',
    readTimeEN: '5 min read',
    readTimeAR: '٥ دقائق قراءة',
    date: '15 May 2026',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqxz2yV6Txg1Ylp40OjIw39_JzxcPzcHubVUqCSQjZaFpglU6tL2Sx6kaTyk5Ze_kSNZ2-8-Qph3MIpT0MUVfZbWYtNNfVmcG5_iHWcdZCE7WVgEKNtElpUuHYoL2k1_TKn-B2GeOYA0V3NjKpaUZ7IP1CRuiSZGqNao43nsTbs5kYIe9EV9pAkSA9gLIoxMXbmrheG4xLwUgaygPYbeQAx810fqP1wjiUHbK-iCZJInYlaSkpbDipGYqYuLGrrYPLN86cqBebFl6s',
    badgeEN: 'Featured Post',
    badgeAR: 'مقال مختار',
    contentEN: 'Modern structural glazing has transcended pure aesthetics, evolving into key functional envelopes that manage energy. This deep dive reviews electrochromic innovations, low-iron transparency parameters, and high-wind structural glass performance metrics across Saudi Arabias mega structures.',
    contentAR: 'لم تعد الواجهات الزجاجية مجرد عنصر جمالي بحت، بل تحولت إلى غلاف هندسي نشط يوفر عزلًا جبارًا للحرارة في ظروف المملكة الحارة. بفضل تقنيات تظليل الزجاج التلقائي ومقاومة ضغط الرياح العال، نستعرض أحدث معايير الأمان والاستدامة في الواجهات لتقليل تكلفة المكيفات بطلب عالمي.'
  },
  {
    id: '2',
    titleEN: 'Signing of Phase II for the Riyadh International Tower Facades',
    titleAR: 'توقيع عقد المرحلة الثانية لتطوير واجهات برج الرياض الدولي',
    excerptEN: 'Al-Fahd Contracting secures the major installation and cladding agreement for Riyadh’s prominent landmark.',
    excerptAR: 'أعلنت الفهد للمقاولات عن شراكة جديدة وتوقيع اتفاقية توريد وتجهيز أنظمة واجهات متكاملة لأحد كبرى الأبراج الاستثمارية بالرياض.',
    categoryEN: 'Company News',
    categoryAR: 'مشاريع الشركة',
    readTimeEN: '3 min read',
    readTimeAR: '٣ دقائق قراءة',
    date: '10 May 2026',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC47ms1XX8nur_QJz9udfz200farLOcBgEo2EcD8urd7YkAQoa5ZoVofVAQXzczuWZZQxInqG4msiee86bXeGCebBprae1LJWz7NwukGpZyD40qGsR912J8egmHRuvGw9LTlCuTRWlbndIdTJ3FrPuWGlPpeESCtP06FuNqszpTJBV_qgjzdN59DjjndbUqtnnsav6MpKMgBSKasENXAi6oT38lWxTAWiS16v-SSYwMb_cAa7xChfdhvLgqm9mfLgePujX2zYWFW1oM',
    contentEN: 'Al-Fahd Contracting has officially signed the phase II contract to customize and erect the double-glazed engineered aluminum cladding for the Riyadh International Tower, a masterwork of modern structural architecture.',
    contentAR: 'تم بحمد الله توقيع عقد المرحلة الثانية لبرج الرياض الدولي لتخصيص الواجهات المزدوجة العازلة للألمنيوم المعماري والزجاج الإنشائي مع ضمانات كاملة ومطابقة لأرفع شهادات المنشأ الأوروبي والآسيوي.'
  },
  {
    id: '3',
    titleEN: 'Thermal Insulation Impact on Facade Energy Consumption in Desert Climates',
    titleAR: 'تأثير العزل الحراري في الواجهات على استهلاك الطاقة في المناخ الصحراوي',
    excerptEN: 'An analytical research on optimizing thermal break profiles for sustainable HVAC load reduction in KSA.',
    excerptAR: 'دراسة هندسية تحليلية حول أهمية تكنولوجيا الحواجز الحرارية لتقليل أحمال التكييف وتوفير الطاقة بشكل فعال ومطابق للأكواد الوطنية.',
    categoryEN: 'Technical Studies',
    categoryAR: 'دراسات تقنية',
    readTimeEN: '8 min read',
    readTimeAR: '٨ دقائق قراءة',
    date: '05 May 2026',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAw42ezMjfdpd-lA7_MW4p08Sop1r62HU8fY-tIf_mp0-Y4E1fQ0vkKswn7-ehKYrfYSGGNsB3vWsN8nOpDb5lshtj5VwUeeTKZQ5FWgm08KvRdaErnyqv3fF8E6jgOjc-3k4MAO1I7WZKhee9CgPDdFDbi0UVaGCUs85GuanN5fPu-6a7_C2ogyQXqdO-lie-nGV6yd3sNjsDhJD00m_R4hJ158xpOdcFA4qFElmiXfAJb6xnfRTH2YT5Nxk_9zhue72cSRIYfdJ__',
    contentEN: 'This comprehensive architectural research evaluates the synergy of low-E thermal breaks and insulated glass units in mitigating harsh UV radiation, allowing substantial peak-electricity usage savings.',
    contentAR: 'تستعرض الدراسة تجارب الواقع المعززة التي قمنا بها في مصانع الفهد لتقنيات العزل المتقدمة بمطابقة معايير كود البناء السعودي لتقليل نقل أشعة الحرارة المنبعثة من النوافذ بمتوسط كفاءة إنشائية ملحوظة.'
  }
];

export const TRANSLATIONS = {
  en: {
    brand: 'Al-Fahd',
    fullName: 'Al-Fahd Contracting',
    portal: 'Client Portal',
    navHome: 'Home',
    navAbout: 'About Us',
    navServices: 'Services',
    navProjects: 'Projects',
    navBlog: 'Blog',
    navContact: 'Contact Us',
    ctaQuote: 'Get a Quote',
    langToggle: 'العربية',
    searchPlaceholder: 'Search projects & studies...',
    footerDesc: 'Leading the industry in specialized contracting and high-performance engineering systems for the modern world since 1984.',
    copyright: '© 2026 Al-Fahd Contracting. All Rights Reserved. ISO 9001 Certified.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    compliance: 'Compliance',
    specialties: 'Specialties',
    companyLinks: 'Company',
    aluminum: 'Aluminum Systems',
    curtainWall: 'Curtain Walls',
    glass: 'Structural Glass',
    steel: 'Steel Structures',
    ourHistory: 'Our History',
    leadership: 'Leadership',
    careers: 'Careers',
    officeHours: 'Open Sun-Thu, 8:00 AM - 5:00 PM',
    mapTitle: 'Regional Headquarters',
    mapLoc: 'Riyadh Financial District',
    directions: 'Directions',
    beginInquiry: 'Begin Inquiry',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    rfqTitle: 'Request for Quotation',
    step1: 'Details',
    step2: 'Specs',
    step3: 'Review',
    formFullName: 'Full Name',
    formCompany: 'Company / Organization',
    formProjectType: 'Project Type',
    formScope: 'Estimated Project Scope',
    formScopePlace: 'Briefly describe structural rules, dimensions and engineering blueprints...',
    formPlaceholderName: 'Engineering Manager / Architect Name',
    formPlaceholderCompany: 'Firm Name',
    btnLaunchInquiry: 'Send Professional Inquiry',
    btnTransmitting: 'TRANSMITTING INQUIRY...',
    btnSecured: 'INQUIRY SECURED',
    uploadZone: 'Attach Blueprints (PDF/DWG/Images)',
    uploadSuccess: 'File Attached Successfully: ',
    heroBadge: 'Connect with Excellence',
    heroTag: 'Partner With Al-Fahd',
    heroDesc: 'Our engineering teams are ready to transform your architectural vision into a structural masterpiece.',
    statsTrust: 'Years of Trust',
    statsProjects: 'Projects Delivered',
    statsProduction: 'Production Floor (SQM)',
    leadershipTitle: 'Corporate Leadership',
    leadershipFounder: 'Chairman & Founder',
    leadershipVisionBtn: 'Read Full Vision',
    factoryFloorBadge: 'The Factory Floor',
    factoryFloorTitle: 'Fabrication Precision',
    pillarsTitle: 'The Elite Pillars',
    pillars: [
      { num: '01', title: 'Structural Integrity', text: 'Exceeding international ASTM and ISO standards in every joint, seal, and structural member.' },
      { num: '02', title: 'Visionary Craft', text: 'Translating the boldest architectural sketches into feasible, enduring physical realities.' },
      { num: '03', title: 'Environmental Synergy', text: 'Thermal-break technology optimized for the harshest desert climates of the Middle East.' }
    ],
    ctaForgeTitle: 'READY TO FORGE EXCELLENCE?',
    ctaForgeDesc: 'Partner with Al-Fahd for your next landmark development. Consultation with our engineering board is available upon request.',
    servicesSub: 'TIGHT INTEGRATION WITH INNOVATIVE TOOLS',
    servicesTitle: 'Engineering Workflow',
    servicesDesc: 'Providing a robust chain of design, processing, and assembly for majestic corporate buildings.',
    serviceItems: [
      { id: '01', title: 'Technical Consultancy', text: 'Feasibility studies and structural analysis conducted by lead engineers to ensure project viability.' },
      { id: '02', title: 'Precision Fabrication', text: 'CNC-controlled manufacturing within our ISO 9001 certified facilities for micron-level accuracy.' },
      { id: '03', title: 'Elite Installation', text: 'On-site execution by specialized teams using advanced logistics and safety protocols.' }
    ],
    viewArchive: 'View Complete Archive',
    allCat: 'All Projects',
    bentoHeader: 'Integrated Systems',
    bentoSub: 'Harmonizing materials to create icons of permanence.',
    metalStructures: 'Heavy Industry Steel Systems',
    customGlaLoad: 'Load-Bearing Structural Systems',
    newsletterTitle: 'Newsletter Registration',
    newsletterSub: 'Sign up to receive our latest technological studies and engineering updates.',
    subscribeBtn: 'Subscribe Now',
    submitting: 'Subscribing...',
    subscribed: 'Thank you for subscribing!',
    viewInPortal: 'View and track incoming RFQ proposals',
    contactSidebarTitle: 'Contact Information',
    contactSidebarDesc: 'Whether seeking technical engineering consultations or visiting our state-of-the-art regional plants, we welcome you.',
    digitalChannels: 'Digital Channels'
  },
  ar: {
    brand: 'الفهد',
    fullName: 'الفهد للمقاولات',
    portal: 'بوابة العملاء',
    navHome: 'الرئيسية',
    navAbout: 'من نحن',
    navServices: 'خدماتنا',
    navProjects: 'مشاريعنا',
    navBlog: 'المدونة',
    navContact: 'اتصل بنا',
    ctaQuote: 'اطلب عرض سعر',
    langToggle: 'English',
    searchPlaceholder: 'ابحث عن المشاريع والدراسات المعمارية...',
    footerDesc: 'الشركة الرائدة في مجال مقاولات الألمنيوم والزجاج والهياكل المعدنية المعقدة في المملكة العربية السعودية منذ عام ١٩٨٤.',
    copyright: '© ٢٠٢٦ مؤسسة الفهد للمقاولات. جميع الحقوق محفوظة. حاصلون على شهادة ISO 9001.',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'الشروط والأحكام',
    compliance: 'الامتثال والمعايير',
    specialties: 'التخصصات',
    companyLinks: 'الشركة',
    aluminum: 'أنظمة الألمنيوم',
    curtainWall: 'جدران الستائر',
    glass: 'الزجاج الإنشائي',
    steel: 'الهياكل المعدنية',
    ourHistory: 'تاريخنا المعماري',
    leadership: 'مجلس الإدارة',
    careers: 'فرص العمل',
    officeHours: 'الأحد - الخميس: ٨:٠٠ صباحًا - ٥:٠٠ مساءً',
    mapTitle: 'المقر الرئيسي للمجموعة',
    mapLoc: 'مركز الملك عبدالله المالي، الرياض',
    directions: 'عرض الاتجاهات',
    beginInquiry: 'ابدأ الاستفسار والطلب',
    callUs: 'اتصل بنا مباشرة',
    emailUs: 'مراسلات المشاريع',
    rfqTitle: 'طلب عرض سعر للمشروع',
    step1: 'معلومات عامة',
    step2: 'المواصفات الفنية',
    step3: 'المراجعة النهائية',
    formFullName: 'الاسم بالكامل',
    formCompany: 'اسم الشركة / المؤسسة المطورة',
    formProjectType: 'تصنيف المشروع المطلوب',
    formScope: 'المواصفات الفنية التقريبية للمشروع',
    formScopePlace: 'يرجى وصف تفاصيل الأبعاد، وسماكة الزجاج أو أنظمة الألمنيوم والهيكل المعدني المطلوب...',
    formPlaceholderName: 'اسم مدير المشروع / المهندس المسؤول',
    formPlaceholderCompany: 'الشركة المطورة أو الاستشارية للمشروع',
    btnLaunchInquiry: 'تقديم طلب عرض السعر للمهندسين',
    btnTransmitting: 'جاري transmitting البيانات...',
    btnSecured: 'تم إرسال وقبول الطلب بنجاح',
    uploadZone: 'اضغط لتحديد أو اسحب ملفات المخططات (PDF/DWG/صور)',
    uploadSuccess: 'تم إرفاق الملف بنجاح: ',
    heroBadge: 'التميز والهندسة المتكاملة تضمن الأمان',
    heroTag: 'حلول متكاملة للألمنيوم والزجاج والحديد',
    heroDesc: 'فريقنا الهندسي مستعد لمناقشة أدق التفاصيل التقنية لمشروعك وتقديم حلول مبتكرة تجمع بين القوة والجمال.',
    statsTrust: 'عامًا من القيادة وبناء الثقة',
    statsProjects: 'مشروع معماري متكامل منجز',
    statsProduction: 'مساحة أرضية الإنتاج الفني (م٢)',
    leadershipTitle: 'Corporate Leadership',
    leadershipFounder: 'رئيس مجلس الإدارة والمؤسس',
    leadershipVisionBtn: 'قراءة الرؤية الكاملة لمستقبل الواجهات',
    factoryFloorBadge: 'صناعة وصياغة الواجهات',
    factoryFloorTitle: 'Fabrication Precision',
    pillarsTitle: 'ركائز التفوق الهيكلي',
    pillars: [
      { num: '٠١', title: 'Structural Integrity', text: 'تحقيق وتجاوز كافة المعايير الهندسية الصارمة لكود البناء السعودي وكود ASTM العالمي.' },
      { num: '٠٢', title: 'Visionary Craft', text: 'تحويل أجرأ الرسومات المعمارية الصعبة إلى هياكل ملموسة قائمة تحبس الأنفاس.' },
      { num: '٠٣', title: 'Environmental Synergy', text: 'أجود تكنولوجيا الحواجز الحرارية (Thermal Breaks) لمقاومة أقسى درجات الحرارة والرمال.' }
    ],
    ctaForgeTitle: 'READY TO FORGE EXCELLENCE?',
    ctaForgeDesc: 'فريقنا جاهز لمناقشة مشروعك القادم وتوفير حلول العزل الفنية المتقدمة وفق أعلى ضمانات الأداء المالي والإنشائي بمملكتنا.',
    servicesSub: 'مسار معتمد بدقة متناهية تحت المليمتر',
    servicesTitle: 'Engineering Workflow',
    servicesDesc: 'نسعى لصنع صروح معمارية تضمن أقصى معايير الاستدامة وعزل الصوت تحت إشراف نخبة من كبار المهندسين.',
    serviceItems: [
      { id: '٠١', title: 'Technical Consultancy', text: 'دراسات الجدوى والتحليل الإنشائي ثلاثي الأبعاد وإلغاء الجسور الحرارية لضمان موثوقية العمل.' },
      { id: '٠٢', title: 'Precision Fabrication', text: 'قص وتجهيز آلي بالروبوتات المتخصصة والـ CNC لجميع القطاعات المعقدة بمطابقة معايير الآيزو ٩٠٠١.' },
      { id: '٠٣', title: 'Elite Installation', text: 'عمليات تثبيت دقيقة وتركيب بالموقع تحت إشراف طاقم مهندسين ومشرفي جودة وسلامة مجهزين.' }
    ],
    viewArchive: 'عرض كامل محفظة الأعمال',
    allCat: 'الكل',
    bentoHeader: 'الأنظمة المتكاملة',
    bentoSub: 'مواءمة الخامات بأحدث التقنيات لصنع أيقونات تستحق البقاء لأجيال.',
    metalStructures: 'صناعات فولاذية ثقيلة وهياكل معقدة',
    customGlaLoad: 'هياكل حاملة وأنظمة زجاجية فائقة الوضوح',
    newsletterTitle: 'النشرة البريدية الهندسية',
    newsletterSub: 'اشترك بالنشرة البريدية ليصلك آخر الدراسات والابتكارات الهندسية ومقالات الاستدامة المعاصرة بصورة دورية.',
    subscribeBtn: 'شراكة معرفية - اشترك الآن',
    submitting: 'جاري تأكيد الاشتراك...',
    subscribed: 'شكرًا جزيلاً لتسجيلك! تم إضافتك لقائمتنا بنجاح.',
    viewInPortal: 'متابعة وإدارة طلبات عرض السعر المقدمة',
    contactSidebarTitle: 'معلومات الاتصال',
    contactSidebarDesc: 'سواء كنت تطور أبراجاً تجارية عملاقة أو تبحث عن استشارة فنية خاصة لمشروعك، قنوات تواصلنا مفعلة على مدار الساعة.',
    digitalChannels: 'قنوات الإشهار والتواصل الرقمية'
  }
};
